![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [26]:
import numpy as np
np.__version__

'1.26.0'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [37]:
my_array=np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [28]:
array_true= np.ones((3, 3), dtype=bool)

print(array_true)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [29]:
impares_array= my_array%2!=0

In [30]:
imaparesenarray= my_array[impares_array]
print(imaparesenarray)

[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [31]:
my_array5=my_array.copy()
negativos_array= my_array5%2!=0
my_array5[negativos_array]=-1
print(my_array5)
print(my_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [33]:
my_array6=my_array.copy()
print(np.where(my_array6%2!=0, -1, my_array6))

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [49]:

ej7_1 = my_array.reshape((5,2)) #5 filas x 2 columnas
print(ej7_1)
ej7_2 = my_array.reshape((2,5)) #2 filas x 5 columnas
print(ej7_2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [54]:
a = np.arange(10).reshape(2,-1)
print(a)
b = np.repeat(1, 10).reshape(2,-1)
print(b)
print(np.vstack((a,b)))#concateno en vertical
print(np.hstack((a,b)))#concateno en horizontal

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [58]:
print(np.concatenate([a,b], axis = 1)) #horizontal
print(np.concatenate([a,b], axis = 0)) #vertical

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [59]:
print(np.concatenate([a,b], axis = 1)) #horizontal

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [61]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
comun10=np.intersect1d(a, b)
print(comun10)

[2 4]


## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [65]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [73]:
my_array12=np.arange(10)
print(my_array12)
my_array12_10=my_array12*10
print(my_array12_10)
print(my_array12[0])
print(my_array12[-1])
print(my_array[1:-2])


[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30 40 50 60 70 80 90]
0
9
[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [78]:
my_array13=np.arange(9)
ej7_2 = my_array13.reshape((3,3))
print(ej7_2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [80]:
my_array14=np.arange(1,50,3)
print(my_array14)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [85]:
my_array14=np.arange(4,1,-0.25)
print(my_array14)

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

In [86]:
import matplotlib.pyplot as plt

imagen = plt.imread("./img/numpy.png")
print(type(imagen))
print(imagen.shape)

<class 'numpy.ndarray'>
(306, 765, 4)


array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       ...,

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        ...,
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=uint8)

array([241, 194,  50, 255], dtype=uint8)

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [90]:
my_array17=np.arange(4)
print(my_array17)
print(my_array17.reshape(2,2))

[0 1 2 3]
[[0 1]
 [2 3]]


## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [116]:
my_array18=np.array(np.random.randint(10, size = (4,5,3)))#randoms de 0 a 10 si solo pongo 10
print(my_array18)




[[[8 7 9]
  [9 8 0]
  [5 2 9]
  [5 6 6]
  [7 8 2]]

 [[6 5 8]
  [4 0 2]
  [9 1 3]
  [6 2 6]
  [3 5 0]]

 [[4 0 7]
  [0 0 8]
  [5 8 6]
  [2 5 9]
  [9 2 1]]

 [[4 7 8]
  [4 5 8]
  [8 1 1]
  [1 6 1]
  [9 8 7]]]
[[[13 10 14]
  [14 10 10]
  [15 18 14]
  [17 15 18]
  [10 16 18]]

 [[11 13 17]
  [10 10 11]
  [15 11 17]
  [14 12 15]
  [10 18 17]]

 [[15 14 14]
  [19 14 18]
  [11 10 15]
  [10 16 11]
  [14 10 19]]

 [[11 16 11]
  [15 15 12]
  [15 17 10]
  [16 15 14]
  [15 18 10]]]


In [117]:
my_array18_2=np.array(np.random.randint(10, 20,  size = (4,5,3)))#randoms de 10 a 20 si solo pongo 10
print(my_array18_2)

[[[13 16 19]
  [12 11 19]
  [15 17 11]
  [16 14 16]
  [18 13 19]]

 [[19 19 13]
  [19 11 15]
  [14 16 13]
  [16 12 17]
  [15 11 12]]

 [[11 19 10]
  [16 12 16]
  [16 19 15]
  [14 14 15]
  [11 17 18]]

 [[11 11 16]
  [12 18 13]
  [19 10 11]
  [13 10 11]
  [16 18 13]]]


## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [108]:
print(np.zeros((10,1),dtype=bool))

[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]]


array([[False, False, False, False, False],
       [False, False, False, False, False]])

## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [120]:
x =np.random.randint(10, 20, size = (5,2,6))
print(x)

[[[14 13 16 13 12 18]
  [14 16 10 18 15 18]]

 [[18 17 10 14 10 12]
  [19 15 18 14 10 11]]

 [[11 10 14 16 15 12]
  [11 11 16 16 15 17]]

 [[10 12 11 11 18 14]
  [17 16 14 11 10 11]]

 [[19 12 14 10 18 15]
  [17 18 17 19 13 11]]]


In [127]:
x.size

60

In [126]:
x.ndim

3

In [125]:
x.shape

(5, 2, 6)